branches:
  only:
    - master
language: python
python:
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev
addons:
  postgresql: "9.3"
services:
  - mysql
before_script:
  - pip install aiomysql aiopg 
  - psql -c 'create database test;' -U postgres
  - psql test -c 'CREATE EXTENSION IF NOT EXISTS hstore' -U postgres
  - mysql -e "create database IF NOT EXISTS test;" -uroot
# command to install dependencies
install: "pip install -e ."
# command to run tests
script:
  - python setup.py test
