branches:
  only:
    - master
language: python
matrix:
  include:
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
      dist: xenial
      sudo: true
addons:
  postgresql: "9.6"
services:
  - mysql
before_script:
  - pip install aiomysql aiopg 
  - psql -c 'create database test;' -U postgres
  - psql test -c 'CREATE EXTENSION IF NOT EXISTS hstore' -U postgres
  - mysql -e "create database IF NOT EXISTS test;" -uroot
# command to install dependencies
install: "pip install -e ."
# command to run tests
script:
  - python setup.py test
