branches:
  only:
    - master
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  # - "nightly" # currently points to 3.7-dev
# Enable 3.7 without globally enabling sudo and dist
matrix:
  include:
    - python: "3.7"
      dist: xenial
      sudo: true
addons:
  postgresql: "9.3"
services:
  - mysql
before_script:
  - pip install aiomysql aiopg 
  - psql -c 'create database test;' -U postgres
  - psql test -c 'CREATE EXTENSION IF NOT EXISTS hstore' -U postgres
  - mysql -e "create database IF NOT EXISTS test;" -uroot
# command to install dependencies
install: "pip install -e ."
# command to run tests
script:
  - python setup.py test
