version: '3.3'

services:
  postgres:
    image: postgres
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    command: postgres -c log_statement=all
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

  mysql:
    image: mysql
    ports:
      - ${MYSQL_PORT:-3306}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=mysql
